### ISSUE TITLE
Mailinglist or Github

### ISSUE THREAD

**Issue by floriangosse** [mstoiber/pgp.asc#10]
Hey guys, I know there some people which use mail for project specific communication. But there is no official mailinglist.
Is there anyone interested? Or should we discuss on Github?

What are your opinions?

**Comment by mxstbr** [comment]
That "mailing list" only spawned because I mailed some friends the basic idea of pgp.asc, and looked for feedback. That's why it's not official, and never going to be. :) 

All of the discussion should take place here!
