### ISSUE TITLE
Site 404s

### ISSUE THREAD

**Issue by anselmh** [mstoiber/pgp.asc#16]
http://pgpasc.org/ throws an error atm.

**Comment by JamborJan** [comment]
yep, this one has died. Maybe they got shocked by the heavy investment in keybase and either try to do the same or think it is not worth it any more :-)

**Comment by mxstbr** [comment]
Definitely still worth it, but the Github Pages config is apparently messed up. Trying to fix.

**Comment by mxstbr** [comment]
Neue website ist online! http://pgpasc.org

Hoffentlich sind damit alle Probleme gelöst, dürfte aber ein lokales Problem gewesen sein.
