### ISSUE TITLE
PGP Guide

### ISSUE THREAD

**Issue by mxstbr** [mstoiber/pgp.asc#5]
# Original Post

> Currently, I've linked Curtis Wallens [Introduction to PGP](http://curtiswallen.com/pgp), but the guide should be for TG3 (People who have no idea what PGP is). Even though I really like Curtis' Guide, I think it's better suited for TG2 (People who have heard of PGP and know what it is but aren't using it).
> 
> Does anybody have a recommendations for a very-basic guide, focussing less on the weaker points in the toolchain and more on practically using PGP to encrypt mails?

After searching the internet up and down, I've decided to put together my own very easy guide to PGP from different sources. 
# Current Version
### Why encrypt your mails?

If you are on vacation you might send a picture postcard to a friend or family member with a quick "wish you were here" sort of message. But, if you are writing a personal letter to that same friend or family member you would be more inclined to seal it in an envelope.

If you are mailing a check to pay a bill or perhaps a letter telling a friend or family member that the extra key to your house is hidden under the large rock to the left of the back porch you might use a security envelope with hatched lines to obfuscate or hide the contents of the envelope even better. The post office offers a number of other means of tracking messages- sending the letter certified, asking for a return receipt, insuring the contents of a package, etc.

Why then would you send personal or confidential information in an unprotected email? Sending information like the location of your extra house key under the large rock to the left of the back porch in an unencrypted email is the equivalent of writing it on a postcard for all to see.

Encrypting your email will keep all but the most dedicated hackers from intercepting and reading your private communications.

[Source](http://netsecurity.about.com/cs/emailsecurity/a/aa051004.htm)
### How does it work?

The way PGP (Pretty Good Privacy, the standard we are going to use) works is that you have a public key and a private key (this sort of encryption is also known as Public Key Infrastructure or PKI). You, and only you, will have and use your private key. Your public key is handed out to anyone you choose or even made publicly available.

[Source](http://netsecurity.about.com/cs/emailsecurity/a/aa051004.htm)
#### Keys

If someone wants to send you a message that is meant only for you to see, they would encrypt it using your public key. Your private key is required to decrypt such a message, so even if someone intercepted the email it would be useless gibberish to them. 

It is important to note that you should encrypt all of your messages, not just the confidential or sensitive ones. If you only encrypt a single email message because it contains your credit card information and an attacker is intercepting your email traffic they will see that 99% of your email is unencrypted plain-text, and one message is encrypted. That is like attaching a bright red neon sign that says "Hack Me" to the message.

If you encrypt all of your messages it would be a much more daunting task for even a dedicated attacker to sift through. After investing the time and effort into decrypting 50 messages that just say "Happy Birthday" or "Do you want to golf this weekend?" or "Yes, I agree" the attacker will most likely not waste any more time on your email.

[Source](http://netsecurity.about.com/cs/emailsecurity/a/aa051004.htm)
##### Step 1: Install the GPGTools GPG Suite for OS X

Visit the [GPGTools website](https://gpgtools.org) and download the GPG Suite for OS X. Once downloaded, mount the DMG and click on "Install". Inside the installer, you can stick with all default parameters, except for the "Installation Type". On the "Installation Type" screen, press "Customize" and uncheck the GPGMail package.
##### Step 2: Creating your very own PGP key

When the installer completes, a new app called "GPG Keychain Access" will launch. A small window will pop up and say: "GPG Keychain Access would like to access your contacts." Press "OK." As soon as you press "OK," a second window will pop up that says "Generate a new key pair." Type in your name and your email address. Also, check the box that says "Upload public key after generation." Expand the "Advanced options" section. Increase the key length to 4096, reduce the "Expiration date" to 1 year from today. Press "Generate key." As soon as you press "Generate key," the "Enter passphrase" window will pop up.
###### A brief word about your passphrase

The entire PGP encryption will rest on your passphrase. So, first and foremost, don't use a passphrase that other people know! Pick something only you will know, and others can't guess. And once you have a passphrase selected, don't give it to other people. 
Second, do not use a password, but rather a passphrase -- a sentence. For example, "Pennstate55" is less preferable than "I graduated from Penn State in 1955, ya heard?!" The longer your passphrase, the better. Lastly, make sure your passphrase is something you can remember. Since it is long, there is a tendency you might forget it. Don't. The consequences to that will be dire. Make sure you can remember your passphrase.
##### Back to Step 2

Once you decide on your passphrase, type it in the "Enter passphrase" window. Turn on the "Show typing" option, so you can be 100% sure that you've typed in your passphrase without any spelling errors. When everything looks good, press "OK". You will be asked to reenter the passphrase. Do it, and press "OK". You will then see a message saying, "We need to generate a lot of random bytes..." Wait for it to complete. Et voilà, your PGP key pair is ready to use!
[Source](http://notes.jerzygangi.com/the-best-pgp-tutorial-for-mac-os-x-ever/)
##### Step 3: Set PGP keyboard shortcuts

Next, you will set up four global keyboard shortcuts in OS X.
Open System Preferences, select the "Keyboard" pane, and go to the "Shortucts" tab. On the left hand side, select "Services." Then, on the right, scroll down to the subsection "Text" and look for a bunch of entries that start with "OpenPGP:". Go through each OpenPGP entry, unchecking each one and deleting the keyboard shortcut.

Next, you will enable and set four shortcuts:
- Enable "OpenPGP: Decrypt" and set its shortcut to ⌃⌥⌘- (i.e., control option command minus)
- Enable "OpenPGP: Encrypt" and set its shortcut to ⌃⌥⌘= (i.e., control option command equals)
- Enable "OpenPGP: Sign" and set its shortcut to ⌃⌥⌘[ (i.e., control option command open bracket)
- Enable "OpenPGP: Verify" and set its shortcut to ⌃⌥⌘] (i.e., control option command close bracket)

That's it! You're done setting up PGP with OpenGPG on OS X!
###### Send

Start off by writing your email, then open the GPG Keychain Access app. Press Command-F and type in the email address of the person you are sending your message to. This will search the public key server (a directory of PGP keys) for your friend's PGP key. (If your friend has more than one key, select his most recent one) You will receive a confirmation that your friend's key was successfully downloaded. You can press "Close". You will now see your friend's public key in your keychain, and you can quit GPG Keychain Access and return to writing the email. (You will only need to download your friend's public key once. After that, it will always be available in your keychain until the key expires.) Since you ticked "Upload public key after generation." in Step 2, your public key is now available in the same way!
Select the entire body of the email and press `⌃⌥⌘=` to encrypt it. A window will pop up, asking you who the recipient is. Select the friend's public key you just downloaded, and press "OK". Your entire message is now encrypted! You can press "Send" safely.  
###### Receive

When you receive your encrypted answer, copy the entire body, from, and including, "-----BEGIN PGP MESSAGE---", to, and including, "-----END PGP MESSAGE---". Open your favorite text editor, and paste it. Now select the entire text, and press `⌃⌥⌘-` to decrypt the message. You will immediately be prompted for your PGP passphrase. Type it in and press "OK". You will now see the decrypted message!
##### pgp.asc

pgp.asc is an initiative to decentralize public PGP keys. Even though uploading your keys to a key server is a good idea, it doesn't provide 100% authenticity and you cannot delete old/invalid keys. By uploading your public PGP key in a `pgp.asc` file to the root of your server, it is easily found by going to `http://yoururl.com/pgp.asc`. This guarantees authenticity, since only you have access to your server, as well as currentness, because you can always overwrite the old key with a new one.
##### Step 1: Install Windows Privacy Trey

Visit the [WinPT website](http://winpt.wald.intevation.org/) and download the latest binary version. Run the installer by double clicking the .exe file, and leave everything at default, except if you use a mail client. WinPT comes with plugins for several popular mail clients (e.g. Outlook), and you can install those by selecting them at the "Choose Components" Screen.
##### Step 2: Creating your very own PGP key

When you've finished installing WinPT, the program should start automatically. A warning will appear that it couldn't find any keyrings. Click "Continue", then select "Have WinPT generate a new key pair." Type in your name and your email address. Increase the key length to 4096, reduce the "Expiration date" to 1 year from today. You will then have to enter you passphrase. 
###### A brief word about your passphrase

The entire PGP encryption will rest on your passphrase. So, first and foremost, don't use a passphrase that other people know! Pick something only you will know, and others can't guess. And once you have a passphrase selected, don't give it to other people. 
Second, do not use a password, but rather a passphrase -- a sentence. For example, "Pennstate55" is less preferable than "I graduated from Penn State in 1955, ya heard?!" The longer your passphrase, the better. Lastly, make sure your passphrase is something you can remember. Since it is long, there is a tendency you might forget it. Don't. The consequences to that will be dire. Make sure you can remember your passphrase.
##### Back to Step 2

Once you decide on your passphrase, press "Start" to generate your key pair. (This could take a while depending on your hardware.) Wait for it to complete. Et voilà, your PGP key pair is ready to use!
###### Send

Start off by writing your email, then right click on the WinPT task bar and choose "Key Manager", then the "Key Server" menu. Select a key server near you and search for the e-mail of the friend you want to send the message to. Select the key that you want to add and click "Receive." (If your friend has more than one key, select his most recent one) You will now see your friend's public key in your Key Manager, and you can return to writing the email. (You will only need to download your friend's public key once. After that, it will always be available in your Key Manager until the key expires.)
Select the entire body of the email and press `SHIFT-CTRL-E` ("E" like encrypt) to encrypt it. WinPT will prompt you to select the key of the person you want to send it to. Select the person and you are done, your email is now encrypted! You can press "Send" safely.  
###### Receive

When you receive your encrypted answer, press `SHIFT-CTRL-D` ("D" like decrypt) to decrypt the message. Enter your passphrase when prompted, and assuming that it was encrypted with your public key, WinPT will use your private key to decrypt the e-mail. Congratulations, you just had your first encrypted conversation!
##### pgp.asc

pgp.asc is an initiative to decentralize public PGP keys. Even though uploading your keys to a key server is a good idea, it doesn't provide 100% authenticity and you cannot delete old/invalid keys. By uploading your public PGP key in a `pgp.asc` file to the root of your server, it is easily found by going to `http://yoururl.com/pgp.asc`. This guarantees authenticity, since only you have access to your server, as well as currentness, because you can always overwrite the old key with a new one.
##### Step 1: Install GnuPG

Either visit the [GnuPG website](https://www.gnupg.org/) and download the latest version, or install gnupg via the command line. (E.g. for Debian based systems the command would be `apt-get install gnupg`)
##### Step 2: Creating your first key pair

Run `gpg --gen-key`, and choose the `RSA and RSA` option. (or simply press `ENTER`, it is the default option) Set the key size to `4096` and then set the validity to one year by entering `1y`. Type in your name and your email address, and then you'll be asked for a passphrase.
###### A brief word about your passphrase

The entire PGP encryption will rest on your passphrase. So, first and foremost, don't use a passphrase that other people know! Pick something only you will know, and others can't guess. And once you have a passphrase selected, don't give it to other people. 
Second, do not use a password, but rather a passphrase -- a sentence. For example, "Pennstate55" is less preferable than "I graduated from Penn State in 1955, ya heard?!" The longer your passphrase, the better. Lastly, make sure your passphrase is something you can remember. Since it is long, there is a tendency you might forget it. Don't. The consequences to that will be dire. Make sure you can remember your passphrase.
##### Back to Step 2

Once you decide on your passphrase, type it in. You will then see a message saying, "We need to generate a lot of random bytes..." Wait for it to complete. Et voilà, your PGP key pair is ready to use!
###### Send

Start off by writing your email, then go to a key server (like http://pgp.mit.edu) and search for your friends e-mail. Download his most recent public key, and import it with `gpg --import key.asc`. You will now see your friend's public key listed under `gpg --list-keys`, and you can return to writing the email. (You will only need to download your friend's public key once. After that, it will always be available in your keychain until the key expires.)
Encrypt your mail by entering `gpg --output mail.gpg --encrypt --recipient friend@hisurl.com mail`. Your e-mail is now encrypted, and you can send it safely.  
###### Recieve

When you receive your encrypted answer, enter `gpg --output mail --decrypt mail.gpg` to decrypt the message. Enter your passphrase when prompted, and assuming that it was encrypted with your public key, GnuPG will use your private key to decrypt the e-mail. Congratulations, you just had your first encrypted conversation!
##### Uploading your key to public key servers

Copy your entire public key, from, and including, `-----BEGIN PGP PUBLIC KEY BLOCK-----` to, and including, `-----END PGP PUBLIC KEY BLOCK-----`. Open a key server of your choice (e.g. http://pgp.mit.edu) and simply paste your key in the designated form field. Congratulations, your key is now available to everybody!
##### pgp.asc

pgp.asc is an initiative to decentralize public PGP keys. Even though uploading your keys to a key server is a good idea, it doesn't provide 100% authenticity and you cannot delete old/invalid keys. By uploading your public PGP key in a `pgp.asc` file to the root of your server, it is easily found by going to `http://yoururl.com/pgp.asc`. This guarantees authenticity, since only you have access to your server, as well as currentness, because you can always overwrite the old key with a new one.

**Comment by iamwebrocker** [comment]
Marco just started a series of blog posts that could very well cover this topic: http://www.zehe-edv.de/tag/kryptografie/

**Comment by mxstbr** [comment]
Seems a bit too elaborate, /me thinks. We have to try to convince people to give PGP a try, and that won't be accomplished by lots of explanation. (Sadly...)

Nice in-depth introduction though so far, if it's going to be translated it might fit better than Curtis' Guide!

**Comment by mxstbr** [comment]
I've decided to write my own "Guide to PGP for Dummies". I'll post the whole thing in the first post of the issue, if you have any ideas for improvement, simply comment below.

I'll use a sightly changed version of Tony Bradleys ["Why you should encrypt your E-Mails"](http://netsecurity.about.com/cs/emailsecurity/a/aa051004.htm) for the introduction, as it is quite nice, and there's no need to reinvent the wheel there. (Do I need to get the rights for that, or is it enough if I link to it?)

**Comment by mxstbr** [comment]
Added MacOS Part from [here](http://notes.jerzygangi.com/the-best-pgp-tutorial-for-mac-os-x-ever/)!

EDIT 05.01.: Added `Step 3: Set PGP keyboard shortcuts` and `Step 4: Send and receive secure e-mails` to MacOS Part.

**Comment by mxstbr** [comment]
Wrote Windows Part, with help from [here](http://www.fuzzymonkey.org/articles/pgpguide.shtml) and [here](http://www.clindesc.com/pdf/WinPT-Howto.pdf). 

EDIT 05.01.: Added `Step 3: Send and receive secure e-mails` to Windows Part.

# (Could somebody using Windows confirm this working?)

**Comment by mxstbr** [comment]
Wrote Linux part, with help from [here](http://www.thegeekstuff.com/2012/10/gnupg-basics/) and [here](https://www.gnupg.org/gph/en/manual.html).

EDIT 05.01.: Added `Step 3: Send and receive secure e-mails` to Linux Part.

**Comment by mstoiber** [comment]
I think I'll include the keyservers in the platform specific part, makes more sense tbh.

**Comment by mxstbr** [comment]
Uploaded PGP Guide in branch `feature/pgpguide`. 

Todo:
- [x] Add Tab Layout to OS specific section, with OS X being the auto-open one, Windows the second tab and Linux the last one.

**Comment by johnantoni** [comment]
Good work, I'll read thru it today. Thanks for doing this.

**Comment by mxstbr** [comment]
Added Tab Layout. Pull `feature/pgpguide` and have a look at `pgpguide.html`!
![Tab Layout Screenshot](https://cloud.githubusercontent.com/assets/7525670/5693434/9b9b85ca-991c-11e4-86cf-8cc4c427c9af.png)

@iamwebrocker @anselmh signed off to merge into gh-pages?

**Comment by iamwebrocker** [comment]
I think the tabs should be coupled with ids, so that one could share the url like ...pgpguide.html#win ... pgpguide.html#mac or pgpguide.html#linux and have the corresponding tab open for the visitor of that url. should be easy with :target selector style and js enhancement. Make them tab-key selectable would also be cool.
While I like the screen real estate saving tab pattern, I think for long contents like here it is not the user friendliest solution, mostly b/c of the scrolling inside the page. 
But yes, let's merge and enhance later :-)

**Comment by mxstbr** [comment]
@iamwebrocker I full heartedly agree, but I couldn't find a way to adjust the height without JS. I'll add the id's soon! 

EDIT: Even with IDs, you can't hotlink to a tab, at least I can't seem to get that to work. Maybe I'm doing something wrong? Please try yourself, I pushed the changes.

**Comment by mxstbr** [comment]
(This commit is the one I added the IDs in: 159d692dcbdcbf45f56f54edf3d0ddbb7ffdc422)

**Comment by iamwebrocker** [comment]
ok, i'll look in later. from a first quick glance at the css, i think you need to add #content-1:target rules that duplicate the :selected ~ #content-1 rules, so that a 'targeted' element gets the 'active' styling.
here's an old js fiddle where i tested the :target pseudo element for something similar
http://jsfiddle.net/webrocker/8KLfL/

**Comment by iamwebrocker** [comment]
in https://github.com/mstoiber/pgp.asc/tree/feature-linkable-tabs I added the :target styles. now the hot linking works (kind of), but due to the way the tabs are build with radio/labels, it's difficult to a) make it transparent to the user what link there may be for hotlinking/bookmarking and b) to get the "active" tab set via the url. Without altering the markup of the tab + content structure this is only possible with JS -- but I think a simpler navigation / content markup that enhances progressivly may be an easier approach.
I created a new branch for this, b/c tonight I won't finish the markup changes, work in progress :)

EDIT:
Now the markup is changed, too. The first (and then other active) tab is not changed visually atm, need to check why the '.active' class doesn't apply. Needs further (js)enhancement to trigger the .active class on the tab links. but without the visual indicator it now works + is linkable.

**Comment by iamwebrocker** [comment]
have a look at https://github.com/mstoiber/pgp.asc/commit/d050c055eca2efea099f97f8f7eb9f71b41a3b54

the tabs now have a dash of js to get the 'active' ones styled via the 'active' class. basically it works now, only issues are styling and to set this active state for deep linked tabs, which shouldn't be too hard.
I forced myself to use vanilla js only instead of jquery or else (oh my)…

### in summary:
- tabs are normal links to id anchors now
- the linked anchored divs are styled / made visible vkia the :target selector (to do: may need fallback for old ie)
- so now the tab contents can be viewed/shared directly via link to the anchor
- visual indicator of 'active' tab is set with js, needs more styling refinement (work in progress)
- 'active' tab needs to be set if viewed via direct link (to do)

**Comment by mxstbr** [comment]
@iamwebrocker Nice! I fixed the box-shadow and the hover state for the current active tab, but now the white background weirdly flashes while hovering over non-active tabs. Could you have a look, I couldn't quite find the issue... (Commit b01efb0285e04b2e4b9be24648cef935f25dd876)

**Comment by mxstbr** [comment]
Changed box-shadow to a better looking one and renamed the IDs for the tabs from `#content-1/2/3` to `#osx`, `#windows` and `#linux`, i.e. pgpguide.html#linux now links to the linux part. The shadow under the current active tab doesn't get cleared anymore though, and there still is a weird flash of white when hovering. Anybody got any ideas?

**Comment by JurgisMegnis** [comment]
![02_pgp_desktop_hall](https://cloud.githubusercontent.com/assets/7488270/6096205/2f14ce32-af85-11e4-82cf-a4d99ef084f0.png)
![03_pgp__desktop_guide](https://cloud.githubusercontent.com/assets/7488270/6096206/2f15fb9a-af85-11e4-9398-ef2267023015.png)
![02_pgpasc_mobile_hall](https://cloud.githubusercontent.com/assets/7488270/6096207/3831bb92-af85-11e4-9558-19ed2a521bde.png)

I have created designs for the rest of the pages plus mobile design, so you can see how I imagine the menu and footer on mobile devices. 
For the guide- I don't think that the left bar is necessary for the mobile version of the site. 
Looking forward to comments.

**Comment by mstoiber** [comment]
Nice work again, I like the small logo in the header! 

I think we might run into a problem when there are more people in the Hall of Fame, as the information density is rather low, (I.e. lots of whitespace) so you'd have to scroll a long time to come to the end. Any ideas on how to stuff more people into the same space, and still have it look good? 

Maybe we shouldn't add new members to the bottom, but rather to the top, that way everybody can have their "Five minutes of pgp.asc fame". 

I love the rest of the design, going to start working on it asap!

**Comment by mxstbr** [comment]
Since the PGP guide is now finished and released at http://www.pgpasc.org/pgpguide, I'll close this issue.
